### ISSUE TITLE
Logs in ff_logs.txt are not being saved if dirname=""

### ISSUE THREAD

**Issue by gkoolstra** [eeroqlab/zeroheliumkit#2]
When running the following snippet: 

```
pyff = FreeFEM(config=config, dirname='')
pyff.run(print_log=False)
```

the following error is thrown: 

```
OSError: [Errno 30] Read-only file system: '/ff_logs.txt
```

Suggestion to replace `with open(self.dirname + '/ff_logs.txt, 'w') as outfile:` with `os.path.join(self.dirname, 'ff_logs.txt')`. This should support saving the `ff_logs.txt` file in the same directory.

**Comment by neoh54** [comment]
fixed
